# Generated by Django 3.0.3 on 2020-03-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200310_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_round',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
