# Generated by Django 3.0.3 on 2020-06-07 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200313_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figure',
            name='adjusted_dex',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='adjusted_ma',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='dmg_penalty',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='dodging',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='engaged',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='facing',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='prone',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='tmp_dx_mod',
        ),
        migrations.RemoveField(
            model_name='item',
            name='equipped',
        ),
    ]
