# Generated by Django 3.0.3 on 2020-11-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_game_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='figure_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
